format_version: 10
pipelines:
  prometheus:
    group: Tools
    materials:
      git-2058dd3:
        git: https://github.com/iteration-1/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: ansible-playbook,  arguments:["-i", "prometheus.pappik.online", "tools.yml", "-e", "tool_name=prometheus", "-e", "ansible_user=ec2-user", "ansible_password=DevOps321"], run_if: passed}

