format_version: 10
pipelines:
  tools-tf-destroy:
    group: Terraform
    materials:
      git-2058dd3:
        git: https://github.com/iteration-1/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - APPLY:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec: {command: terraform,  arguments:["init"], run_if: passed}
                - exec: {command: terraform,  arguments: [ "destroy", "-auto-approve" ], run_if: passed }

